// <auto-generated />
namespace Vidly_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addnumberavaliableinmovieclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnumberavaliableinmovieclass));
        
        string IMigrationMetadata.Id
        {
            get { return "202010112218219_addnumberavaliableinmovieclass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
