// <auto-generated />
namespace Vidly_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewClassMemberShipTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewClassMemberShipTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "202009221218002_NewClassMemberShipTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
